import { useEffect, useState } from "react";

type Language = "en" | "es";

type InfoBlock =
  | { kind: "p"; text: string }
  | { kind: "list"; items: string[] };

type InfoSection = {
  title: string;
  emoji: string;
  /** Single-paragraph text. Ignored when `blocks` is provided. */
  content: string;
  /** For sections that need several paragraphs or a list. */
  blocks?: InfoBlock[];
};

const CONTENT: Record<Language, { title: string; intro: string; sections: InfoSection[] }> = {
  en: {
    title: "Tournament Info",
    intro:
      "This tournament is all about good energy, fair play, and enjoying beach volleyball together. Keep it competitive but relaxed, no stress, just great games and positive vibes. 🏖️🏐",
    sections: [
      {
        title: "Beach Volleyball Rules",
        emoji: "🏐",
        content:
          "Standard beach volleyball rules apply. No bad finger setting, no open-hand receive or attack, and no double touches."
      },
      {
        title: "Self-Judgment",
        emoji: "🤝",
        content:
          "There are no referees. Players are trusted to judge their own matches fairly. If there is any doubt, replay the point."
      },
      {
        title: "Match Format",
        emoji: "⚔️",
        content:
          "Each player will play 7 matches during the tournament. All matches are played to 21 points. If the score reaches 20–20, the game continues until a team wins by 2 points."
      },
      {
        title: "Separate Play",
        emoji: "👨‍👩‍👧",
        content:
          "Male and female players compete on separate nets. There are nets for males and nets for females, each set to the correct competition height."
      },
      {
        title: "Different Partners",
        emoji: "🤼",
        content:
          "Each match is played with a different partner. Players collect points individually, so aim to perform well in every match."
      },
      {
        title: "Random Team Selection",
        emoji: "🎲",
        content:
          "Teams for each match are randomly generated by the system to ensure fairness and varied matchups."
      },
      {
        title: "On-Court Scorekeeping",
        emoji: "📊",
        content:
          "Each team assigns one player to keep track of the score. The score must be called out loud before every serve."
      },
      {
        title: "Score Submission",
        emoji: "📥",
        content:
          "After each match, one player submits the final score in the app, only after both teams agree on the result."
      },
      {
        title: "Point System",
        emoji: "🏆",
        content:
          "Players on the winning team receive 2 points each. Players on the losing team receive 1 point each."
      },
      {
        title: "Automatic Tracking",
        emoji: "🤖",
        content:
          "The app automatically tracks match results, individual points, and player rankings. Rankings update immediately after a score is submitted."
      },
      {
        title: "Tiebreaker Rules",
        emoji: "⚖️",
        content:
          "If players are tied on points, ranking is decided by total score, then point difference, then head-to-head results, then strength of opponents. If still tied, a final rule such as player ID is used to ensure a unique ranking."
      },
      {
        title: "Final Match & Titles",
        emoji: "👑",
        content: "",
        blocks: [
          {
            kind: "p",
            text: "After the initial 7 matches, the top 2 ranked females and top 2 ranked males qualify for the final mixed match, which is the 8th match."
          },
          { kind: "p", text: "The final teams are formed as follows:" },
          {
            kind: "list",
            items: ["1st ranked male + 1st ranked female", "2nd ranked male + 2nd ranked female"]
          },
          {
            kind: "p",
            text: "The final is played as a best-of-3 sets match. The first two sets are played to 21 points. If needed, the third set is played to 15 points."
          },
          {
            kind: "p",
            text: "The winning team in the final match will be crowned King and Queen of the Beach. The losing team will be named Prince and Princess of the Beach."
          }
        ]
      }
    ]
  },
  es: {
    title: "Información del Torneo",
    intro:
      "Este torneo se trata sobre buena energía, juego limpio y disfrutar juntos del vóley playa. Mantén la competencia pero relajada, sin estrés, solo buenos partidos y buen ambiente. 🏖️🏐",
    sections: [
      {
        title: "Reglas del Vóley Playa",
        emoji: "🏐",
        content:
          "Se aplican las reglas estándar del vóley playa. No se permite tocar el balón con un solo dedo, ni recibir o atacar con la mano abierta, ni dar dos toques."
      },
      {
        title: "Autoarbitraje",
        emoji: "🤝",
        content:
          "No hay árbitros. Se confía en que los jugadores juzguen sus propios partidos con justicia. Si hay cualquier duda, se repite el punto."
      },
      {
        title: "Formato de Partido",
        emoji: "⚔️",
        content:
          "Cada jugador disputará 7 partidos durante el torneo. Todos los partidos se juegan a 21 puntos. Si el marcador llega a 20–20, el partido continúa hasta que un equipo gane por 2 puntos."
      },
      {
        title: "Juego Separado",
        emoji: "👨‍👩‍👧",
        content:
          "Los jugadores masculinos y femeninos compiten en redes separadas. Hay redes para hombres y redes para mujeres, cada una ajustada a la altura correcta de competición."
      },
      {
        title: "Compañeros Diferentes",
        emoji: "🤼",
        content:
          "Cada partido se juega con un compañero diferente. Los jugadores acumulan puntos individualmente, así que esfuérzate en cada partido."
      },
      {
        title: "Selección Aleatoria de Equipos",
        emoji: "🎲",
        content:
          "Los equipos de cada partido se generan al azar en la aplicación para garantizar la equidad y una variedad de cruces."
      },
      {
        title: "Marcador en la Pista",
        emoji: "📊",
        content:
          "Cada equipo designa a un jugador para llevar el marcador. El puntaje debe anunciarse en voz alta antes de cada saque."
      },
      {
        title: "Envío del Resultado",
        emoji: "📥",
        content:
          "Después de cada partido, un jugador introduce el resultado final en la aplicación, solo cuando ambos equipos están de acuerdo."
      },
      {
        title: "Sistema de Puntos",
        emoji: "🏆",
        content:
          "Los jugadores del equipo ganador reciben 2 puntos cada uno. Los jugadores del equipo perdedor reciben 1 punto cada uno."
      },
      {
        title: "Seguimiento Automático",
        emoji: "🤖",
        content:
          "La aplicación registra automáticamente los resultados, los puntos individuales y la clasificación. El ranking se actualiza inmediatamente después de enviar un resultado."
      },
      {
        title: "Reglas de Desempate",
        emoji: "⚖️",
        content:
          "Si los jugadores están empatados en puntos, el orden se decide por la puntuación total, luego por la diferencia de puntos, luego por los resultados directos entre ellos y finalmente por la fuerza de los rivales. Si el empate persiste, se aplica una regla final, como el ID del jugador, para garantizar una clasificación única."
      },
      {
        title: "Final y Títulos",
        emoji: "👑",
        content: "",
        blocks: [
          {
            kind: "p",
            text: "Tras los 7 partidos iniciales, las 2 mejores clasificadas femeninas y los 2 mejores clasificados masculinos se clasifican para la final mixta, que es el octavo partido."
          },
          { kind: "p", text: "Los equipos de la final se forman de la siguiente manera:" },
          {
            kind: "list",
            items: ["Masculino 1.º + Femenino 1.ª", "Masculino 2.º + Femenino 2.ª"]
          },
          {
            kind: "p",
            text: "La final se juega al mejor de 3 sets. Los dos primeros sets se juegan a 21 puntos. Si es necesario, el tercer set se juega a 15 puntos."
          },
          {
            kind: "p",
            text: "El equipo ganador de la final será coronado Rey y Reina de la Playa. El equipo perdedor será nombrado Príncipe y Princesa de la Playa."
          }
        ]
      }
    ]
  }
};

const STORAGE_KEY = "kq-info-language";

/** Remembered choice wins; otherwise follow the browser language if it is Spanish. */
function initialLanguage(): Language {
  try {
    const saved = window.localStorage.getItem(STORAGE_KEY);
    if (saved === "en" || saved === "es") return saved;
  } catch {
    // localStorage unavailable (private mode) - fall through to detection
  }
  return typeof navigator !== "undefined" && navigator.language?.toLowerCase().startsWith("es")
    ? "es"
    : "en";
}

export default function InfoPage() {
  const [language, setLanguage] = useState<Language>(initialLanguage);

  useEffect(() => {
    try {
      window.localStorage.setItem(STORAGE_KEY, language);
    } catch {
      // Preference simply will not persist
    }
    document.documentElement.lang = language;
  }, [language]);

  const { title, intro, sections } = CONTENT[language];

  return (
    <div className="min-h-screen bg-sand-gradient px-4 py-6">
      <div className="max-w-lg mx-auto space-y-6 animate-fade-in">
        {/* Header */}
        <header className="text-center space-y-4">
          <div className="pt-4">
            <div className="text-5xl mb-3 animate-bounce-gentle">🏐</div>
            <h1 className="text-3xl md:text-4xl font-bold text-transparent bg-beach-gradient bg-clip-text drop-shadow-sm">
              {title}
            </h1>
            <div className="w-16 h-1 bg-sunset mx-auto rounded-full mt-3"></div>

            {/* Language picker - stays on this page only */}
            <div
              role="group"
              aria-label="Language / Idioma"
              className="inline-flex items-center gap-1 mt-4 p-1 rounded-full bg-white/80 backdrop-blur-sm border border-sand-dark/20 shadow-beach"
            >
              {(["en", "es"] as Language[]).map((code) => (
                <button
                  key={code}
                  type="button"
                  onClick={() => setLanguage(code)}
                  aria-pressed={language === code}
                  className={
                    "px-4 py-1.5 rounded-full text-sm font-bold uppercase tracking-wide transition-all duration-200 " +
                    (language === code
                      ? "bg-ocean text-white shadow-beach"
                      : "text-foreground/70 hover:bg-ocean/15 hover:text-ocean")
                  }
                >
                  {code}
                </button>
              ))}
            </div>
          </div>
        </header>

        {/* Intro Text */}
        <div className="bg-white/80 backdrop-blur-sm rounded-2xl p-6 shadow-beach border border-sand-dark/20">
          <p className="text-base leading-relaxed text-foreground">
            {intro}
          </p>
        </div>

        {/* Info Sections */}
        <div className="space-y-6">
          {sections.map((section, index) => (
            <div
              key={index}
              className="bg-white/80 backdrop-blur-sm rounded-2xl p-6 shadow-beach border border-sand-dark/20"
            >
              <h2 className="text-xl font-bold text-ocean mb-3 flex items-center gap-2">
                <span className="text-2xl">{section.emoji}</span>
                {section.title}
              </h2>
              {section.blocks ? (
                <div className="space-y-3">
                  {section.blocks.map((block, blockIndex) =>
                    block.kind === "list" ? (
                      <ul
                        key={blockIndex}
                        className="list-disc pl-6 space-y-1 marker:text-ocean"
                      >
                        {block.items.map((item) => (
                          <li
                            key={item}
                            className="text-base leading-relaxed text-foreground"
                          >
                            {item}
                          </li>
                        ))}
                      </ul>
                    ) : (
                      <p key={blockIndex} className="text-base leading-relaxed text-foreground">
                        {block.text}
                      </p>
                    )
                  )}
                </div>
              ) : (
                <p className="text-base leading-relaxed text-foreground">
                  {section.content}
                </p>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}