import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { ArrowLeft, Info } from "lucide-react";

export default function InfoPage() {
  const navigate = useNavigate();

  const tournamentInfo = [
    {
      title: "Beach Volleyball Rules",
      emoji: "🏐",
      content: "Standard beach volleyball rules apply. No bad finger setting, no open-hand receive or attack, and no double touches."
    },
    {
      title: "Self-Judgment",
      emoji: "🤝",
      content: "There are no referees. Players are trusted to judge their own matches fairly. If there is any doubt, replay the point."
    },
    {
      title: "Match Format",
      emoji: "⚔️",
      content: "Each player will play 7 matches during the tournament. All matches are played to 21 points. If the score reaches 20–20, the game continues until a team wins by 2 points."
    },
    {
      title: "Separate Play",
      emoji: "👨‍👩‍👧",
      content: "Male and female players compete on separate nets. There are nets for males and nets for females, each set to the correct competition height."
    },
    {
      title: "Different Partners",
      emoji: "🤼",
      content: "Each match is played with a different partner. Players collect points individually, so aim to perform well in every match."
    },
    {
      title: "Random Team Selection",
      emoji: "🎲",
      content: "Teams for each match are randomly generated by the system to ensure fairness and varied matchups."
    },
    {
      title: "On-Court Scorekeeping",
      emoji: "📊",
      content: "Each team assigns one player to keep track of the score. The score must be called out loud before every serve."
    },
    {
      title: "Score Submission",
      emoji: "📥",
      content: "After each match, one player submits the final score in the app, only after both teams agree on the result."
    },
    {
      title: "Point System",
      emoji: "🏆",
      content: "Players on the winning team receive 2 points each. Players on the losing team receive 1 point each."
    },
    {
      title: "Automatic Tracking",
      emoji: "🤖",
      content: "The app automatically tracks match results, individual points, and player rankings. Rankings update immediately after a score is submitted."
    },
    {
      title: "Tiebreaker Rules",
      emoji: "⚖️",
      content: "If players are tied on points, ranking is decided by total score, then point difference, then head-to-head results, then strength of opponents. If still tied, a final rule such as player ID is used to ensure a unique ranking."
    },
    {
      title: "Final Match & Titles",
      emoji: "👑",
      content: "After the initial 7 matches, the top 2 ranked females and top 2 ranked males qualify for the final mixed match, which is the 8th match. The final is best of 3 sets. The first two sets are played to 21 points. If needed, the third set is played to 15 points. The winning team in the final match will be crowned King and Queen of the Beach. The losing team will be named Prince and Princess of the Beach."
    }
  ];

  return (
    <div className="min-h-screen bg-sand-gradient px-4 py-6">
      <div className="max-w-lg mx-auto space-y-6 animate-fade-in">
        {/* Header */}
        <header className="text-center space-y-4">
          <Button
            variant="outline"
            onClick={() => navigate('/')}
            className="w-full touch-target bg-white/70 hover:bg-ocean hover:text-white border-ocean/30 text-ocean transition-all duration-300"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Home
          </Button>

          <div className="pt-4">
            <div className="text-5xl mb-3 animate-bounce-gentle">🏐</div>
            <h1 className="text-3xl md:text-4xl font-bold text-transparent bg-beach-gradient bg-clip-text drop-shadow-sm">
              Tournament Info
            </h1>
            <div className="w-16 h-1 bg-sunset mx-auto rounded-full mt-3"></div>
          </div>
        </header>

        {/* Intro Text */}
        <div className="bg-white/80 backdrop-blur-sm rounded-2xl p-6 shadow-beach border border-sand-dark/20">
          <p className="text-base leading-relaxed text-foreground">
            This tournament is all about good energy, fair play, and enjoying beach volleyball together. Keep it competitive but relaxed, no stress, just great games and positive vibes. 🏖️🏐
          </p>
        </div>

        {/* Info Sections */}
        <div className="space-y-6">
          {tournamentInfo.map((section, index) => (
            <div
              key={index}
              className="bg-white/80 backdrop-blur-sm rounded-2xl p-6 shadow-beach border border-sand-dark/20"
            >
              <h2 className="text-xl font-bold text-ocean mb-3 flex items-center gap-2">
                <span className="text-2xl">{section.emoji}</span>
                {section.title}
              </h2>
              <p className="text-base leading-relaxed text-foreground">
                {section.content}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
