import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Crown, Users, Info } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { supabase } from "@/integrations/supabase/client";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

export default function Landing() {
  const navigate = useNavigate();
  const [isAdminRegistered, setIsAdminRegistered] = useState(false);
  const [showInfoModal, setShowInfoModal] = useState(false);

  useEffect(() => {
    checkAdminStatus();
  }, []);

  const checkAdminStatus = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      // In a real app, you would check if the user has admin role
      // For now, we'll just check if user is authenticated
      setIsAdminRegistered(!!user);
    } catch (error) {
      console.error("Error checking admin status:", error);
    }
  };

  const handleAdminClick = () => {
    navigate('/admin/login');
  };

  const handlePlayerClick = () => {
    navigate('/player-access');
  };

  const handleInfoClick = () => {
    setShowInfoModal(true);
  };

  const tournamentInfo = `**King & Queen Tournament Info**

This tournament is all about good energy, fair play, and enjoying beach volleyball together. Keep it competitive but relaxed, no stress, just great games and positive vibes. 🏖️🏐

Beach Volleyball Rules 🏐
Standard beach volleyball rules apply. No bad finger setting, no open-hand receive or attack, and no double touches.

Self-Judgment 🤝
There are no referees. Players are trusted to judge their own matches fairly. If there is any doubt, replay the point.

Match Format ⚔️
Each player will play 7 matches during the tournament. All matches are played to 21 points. If the score reaches 20–20, the game continues until a team wins by 2 points.

Separate Play 👨‍👩‍👧
Male and female players compete on separate nets. There are two nets for males and two for females, each set to the correct competition height.

Different Partners 🤼
Each match is played with a different partner. Players collect points individually, so aim to perform well in every match.

Random Team Selection 🎲
Teams for each match are randomly generated by the system to ensure fairness and varied matchups.

On-Court Scorekeeping 📊
Each team assigns one player to keep track of the score. The score must be called out loud before every serve.

Score Submission 📥
After each match, one player submits the final score in the app, only after both teams agree on the result.

Point System 🏆
Players on the winning team receive 2 points each. Players on the losing team receive 1 point each.

Automatic Tracking 🤖
The app automatically tracks match results, individual points, and player rankings. Rankings update immediately after a score is submitted.

Tiebreaker Rule ⚖️
If players are tied on total points, the total points scored across all matches is used as the tiebreaker. Every point counts.

Final Match & Titles 👑
After the initial 7 matches, the top 2 ranked females and top 2 ranked males qualify for the final mixed match, which is the 8th match.
The final is best of 3 sets. The first two sets are played to 21 points. If needed, the third set is played to 15 points.

The winning team in the final match will be crowned King and Queen of the Beach. 👑
The losing team will be named Prince and Princess of the Beach. 👑`;

  return (
    <div className="min-h-screen bg-sand-gradient px-4 py-6 flex items-center justify-center">
      <div className="w-full max-w-md mx-auto text-center">
        <div className="text-6xl mb-6 animate-bounce-gentle">🏐</div>
        <h1 className="text-3xl md:text-4xl font-bold text-transparent bg-beach-gradient bg-clip-text mb-8 drop-shadow-sm">
          King & Queen of the Beach
        </h1>
        

        
        <div className="space-y-6">
          <Button
            onClick={handleAdminClick}
            className="w-full py-6 text-xl font-bold bg-sunset hover:bg-sunset-dark text-white shadow-beach transition-all duration-300 flex items-center justify-center gap-3"
          >
            <Crown className="w-6 h-6" />
            Admin
          </Button>
          <Button
            onClick={handlePlayerClick}
            className="w-full py-6 text-xl font-bold bg-ocean hover:bg-ocean-dark text-white shadow-beach transition-all duration-300 flex items-center justify-center gap-3"
          >
            <Users className="w-6 h-6" />
            Player
          </Button>
          <Button
            onClick={handleInfoClick}
            className="w-full py-6 text-xl font-bold bg-palm hover:bg-palm-dark text-white shadow-beach transition-all duration-300 flex items-center justify-center gap-3"
          >
            <Info className="w-6 h-6" />
            Info
          </Button>
        </div>
        
        <Dialog open={showInfoModal} onOpenChange={setShowInfoModal}>
          <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>King & Queen Tournament Info</DialogTitle>
            </DialogHeader>
            <div className="text-sm leading-relaxed max-h-[60vh] overflow-y-auto pr-2">
              {tournamentInfo.split('\n').map((line, index) => {
                // Define titles that should be bold
                const titles = [
                  'Beach Volleyball Rules',
                  'Self-Judgment',
                  'Match Format',
                  'Separate Play',
                  'Different Partners',
                  'Random Team Selection',
                  'On-Court Scorekeeping',
                  'Score Submission',
                  'Point System',
                  'Automatic Tracking',
                  'Tiebreaker Rule',
                  'Final Match & Titles'
                ];
                
                // Check if it's the main title
                if (line.startsWith('**') && line.endsWith('**')) {
                  const content = line.slice(2, -2);
                  return (
                    <p key={index} className="font-bold text-center my-4 text-lg text-primary">
                      {content}
                    </p>
                  );
                }
                
                // Check if the line contains a title
                const isTitle = titles.some(title => line.startsWith(title));
                
                if (isTitle) {
                  // Extract title and emoji if present
                  const parts = line.split(' ');
                  const title = parts[0];
                  const emoji = parts.length > 1 && parts[1].match(/[\u{1F600}-\u{1F64F}]|[\u{1F300}-\u{1F5FF}]|[\u{1F680}-\u{1F6FF}]|[\u{1F1E0}-\u{1F1FF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]/u) ? parts[1] : '';
                  const remainingText = parts.slice(emoji ? 2 : 1).join(' ');
                  
                  return (
                    <p key={index} className="font-bold my-2 text-base text-primary">
                      {title} {emoji} {remainingText && <span className="font-normal">{remainingText}</span>}
                    </p>
                  );
                }
                
                return (
                  <p key={index} className="my-1 text-foreground">
                    {line}
                  </p>
                );
              })}
            </div>
          </DialogContent>
        </Dialog>
        
        <div className="mt-8 text-sm text-foreground/60">
          <p>🌊 Beach Volleyball Tournament Tracker 🏖️</p>
          <p className="mt-2 text-xs">
            {isAdminRegistered 
              ? "As an authenticated user, you can access both admin and player features." 
              : "First-time users should register as a player."}
          </p>
        </div>
      </div>
    </div>
  );
}