// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdlmkoxumbyxiygnffcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkbG1rb3h1bWJ5eGl5Z25mZmNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1MTkzMzEsImV4cCI6MjA1NjA5NTMzMX0.zzvQikXloDryyp7c_kS5I-Y660F-gjrL5qqN1a9cNuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);