// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agoczgbxqqjhfyybpywj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnb2N6Z2J4cXFqaGZ5eWJweXdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNjc0MDcsImV4cCI6MjA2Njc0MzQwN30.toFo4FdEeD407GzmW1tOHmhTVR-bTYVQxvoLbCh3Qf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);